server:
  port: 8080

spring:
  application:
    name: gateway
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: playlistRoute
          uri: lb://playlist-service/
          predicate:
            - Path=/playlist/**

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/